import os
import pandas as pd
from google.oauth2 import service_account
from googleapiclient.discovery import build

# 1. Configuration
SPREADSHEET_ID = os.environ.get('SPREADSHEET_ID')
SERVICE_ACCOUNT_FILE = os.path.expanduser('~/.config/rclone/movie-proxy-38fc564bb261.json')
CSV_FILE = 'current_library.csv'
RANGE_NAME = 'Sheet1' # Change 'Sheet1' if your Google Sheet tab has a different name

def main():
    if not SPREADSHEET_ID:
        print("Error: SPREADSHEET_ID environment variable not set.")
        return

    # 2. Authenticate with Google Sheets API
    scopes = ['https://www.googleapis.com/auth/spreadsheets']
    creds = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE, scopes=scopes)
    service = build('sheets', 'v4', credentials=creds)

    # 3. Read the CSV data generated by rclone
    try:
        df = pd.read_csv(CSV_FILE)
        df = df.fillna('') # Fill empty spaces so JSON doesn't break
    except FileNotFoundError:
        print(f"Error: {CSV_FILE} not found.")
        return

    # 4. Prepare data for Sheets API (Headers + Data)
    values = [df.columns.values.tolist()] + df.values.tolist()
    body = {'values': values}

    # 5. Clear the old data first (prevents stale data from remaining at the bottom)
    service.spreadsheets().values().clear(
        spreadsheetId=SPREADSHEET_ID,
        range=RANGE_NAME
    ).execute()

    # 6. Push the new data
    result = service.spreadsheets().values().update(
        spreadsheetId=SPREADSHEET_ID,
        range=RANGE_NAME,
        valueInputOption='USER_ENTERED',
        body=body
    ).execute()

    print(f"Success! {result.get('updatedCells')} cells updated in Google Sheets.")

if __name__ == '__main__':
    main()
